spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: sqli-service-route
              uri: ${SQLI_SERVICE_URI:http://sqli-service:8080}
              predicates:
                - Path=/sqli/**
              filters:
                - RewritePath=/sqli/(?<segment>.*), /$\{segment}

server:
  port: ${SERVER_PORT:8081}
